# Generated by Django 5.0.7 on 2024-08-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wattio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverter',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=120, verbose_name='Название'),
        ),
    ]
