# Generated by Django 5.0.7 on 2024-10-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wattio', '0002_inverter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='plant',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='plant',
            name='power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая мощность'),
        ),
        migrations.AddField(
            model_name='plant',
            name='utc',
            field=models.CharField(default='5', max_length=6, null=True, verbose_name='UTC'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='color',
            field=models.CharField(default='#0cab46', max_length=120, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='name',
            field=models.CharField(choices=[('growatt', 'Growatt'), ('solax', 'SolaX')], max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='serial',
            field=models.CharField(max_length=120, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Название станции'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['name'], name='wattio_plan_name_66835c_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['longitude', 'latitude'], name='wattio_plan_longitu_5897d6_idx'),
        ),
    ]
