# Generated by Django 5.0.7 on 2024-10-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wattio', '0004_remove_plant_wattio_plan_name_66835c_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='plant_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='time_zone',
            new_name='timezone',
        ),
    ]
