# Generated by Django 5.0.7 on 2024-10-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wattio', '0005_rename_plant_image_plant_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, default='plants/cover.jpg', null=True, upload_to='plants/', verbose_name='Изображение станции'),
        ),
    ]
