# Generated by Django 5.0.7 on 2024-10-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wattio', '0006_alter_plant_address_alter_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
    ]
