# Generated by Django 5.0.7 on 2024-10-14 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wattio', '0007_alter_plant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='inverter_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество инверторов'),
        ),
    ]
