# Generated by Django 5.0.7 on 2024-10-16 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wattio', '0008_plant_inverter_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverter',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inverters', to='wattio.plant', verbose_name='Станция'),
        ),
    ]
